// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

type SquareElem struct {
	react.Element
}

func buildSquare(cd react.ComponentDef) react.Component {
	return SquareDef{ComponentDef: cd}
}

func buildSquareElem(props SquareProps, children ...react.Element) *SquareElem {
	return &SquareElem{
		Element: react.CreateElement(buildSquare, props, children...),
	}
}

func (s SquareDef) RendersElement() react.Element {
	return s.Render()
}

// IsProps is an auto-generated definition so that SquareProps implements
// the myitcv.io/react.Props interface.
func (s SquareProps) IsProps() {}

// Props is an auto-generated proxy to the current props of Square
func (s SquareDef) Props() SquareProps {
	uprops := s.ComponentDef.Props()
	return uprops.(SquareProps)
}

func (s SquareProps) EqualsIntf(val react.Props) bool {
	return s == val.(SquareProps)
}

var _ react.Props = SquareProps{}
