// Code generated by reactGen. DO NOT EDIT.

package main

import "myitcv.io/react"

type BoardElem struct {
	react.Element
}

func buildBoard(cd react.ComponentDef) react.Component {
	return BoardDef{ComponentDef: cd}
}

func buildBoardElem(props BoardProps, children ...react.Element) *BoardElem {
	return &BoardElem{
		Element: react.CreateElement(buildBoard, props, children...),
	}
}

func (b BoardDef) RendersElement() react.Element {
	return b.Render()
}

// IsProps is an auto-generated definition so that BoardProps implements
// the myitcv.io/react.Props interface.
func (b BoardProps) IsProps() {}

// Props is an auto-generated proxy to the current props of Board
func (b BoardDef) Props() BoardProps {
	uprops := b.ComponentDef.Props()
	return uprops.(BoardProps)
}

func (b BoardProps) EqualsIntf(val react.Props) bool {
	return b == val.(BoardProps)
}

var _ react.Props = BoardProps{}
